### ISSUE TITLE
Pugs multiline comments

### ISSUE THREAD

**Issue by stasoid** [perl6/Pugs.hs#32]
Can someone please tell how to introduce multiline comment in Pugs?
Perl6 embedded comment doesn't work:
```
#`(
fdsd
)
say 123
```
There is `multiLineComment` in `Lexer.hs`, so I am assuming it supports some kind of multiline comments,
although I can't figure out which one (I don't know Haskell).

**Comment by zoffixznet** [comment]
(on an off chance that you're trying to use Perl 6 rather than specifically its Pugs implementation, note that there hasn't been any commits in this repo since mid-2015 and the compiler that fully supports Perl 6 is currently Rakudo https://rakudo.org/ )

**Comment by stasoid** [comment]
@zoffixznet Yes, I am aware of that.

**Comment by stasoid** [comment]
Pugs multiline comments differ from modern Perl6 embedded comments in two ways: no backtick after `#` and multiline comment must not start at start of the line.
So this doesn't work:
```
#(
fdsd
)
say 123
```
but this works:
```
 #(
fdsd
)
say 123
```
