### ISSUE TITLE
Fine with forking?

### ISSUE THREAD

**Issue by phlummox** [perl6/Pugs.hs#33]
Hi,

I'm hoping to update the [HsPerl5][hsperl5] package contained in this repo to work with recent versions of the ghc compiler (see my initial work [here][phlumm]). If I manage to get it working, I wondered if you'd have any objections to my putting it on Hackage? I'd propose to use a new package name (`hs-perl5`) to distinguish it from the archived version of HsPerl5.

Thanks!

[phlumm]: https://github.com/phlummox/hs-perl5
[hsperl5]: https://github.com/perl6/Pugs.hs/tree/e5fa977f6cf267574d0a2c7d823d0c13a929c38c/HsPerl5

**Comment by JJ** [comment]
By all means, go ahead. If you want, we can give you the commit bit here.

**Comment by JJ** [comment]
But since we haven't given it a lot of love, I think it's much better if, once you work on the fork, we insert a notice here stating that this is no longer maintained and to go to your repo.

**Comment by phlummox** [comment]
No worries - sounds like a good plan! Cheers :)

**Comment by JJ** [comment]
Please tell us when you've got your repo set up, and we'll link it from here.

**Comment by phlummox** [comment]
Done :) - my repo is set up at <https://github.com/phlummox/hs-perl5>, and I've got test cases for the package internals written and passing. Once I have a bit more of it tested, I'll push it to hackage.haskell.org as well.

**Comment by JJ** [comment]
I've given you write permissions, just in case you want to move some (or all) existing issues to the new repository. At any rate, in a few days I'll be archiving this one. Thanks a lot!

**Comment by phlummox** [comment]
Awesome. :) No worries, I'll take a look at the issues and see which ones are worth transferring. And thanks for your help!

**Comment by JJ** [comment]
Archiving it now...
